### ISSUE TITLE
instagram embed is not working

### ISSUE THREAD

**Issue by nicopace** [superdesk/angular-embed#3]
it only works with instagr.am domains... not with instagram.com domain

**Comment by vied12** [comment]
Have you registered the instagram holder ?
https://github.com/superdesk/angular-embed/blob/master/src/angular-embed/handlers/instagram.js#L10

**Comment by nicopace** [comment]
Hi @vied12 ... I found out that the issue was the www. and not the domains.
Shouldn't it work for www instagram urls too?

**Comment by vied12** [comment]
yes it should. The handler needs to be updated.
Thanks for reporting
